client_id = "fce789fe8244b76161b1d196e644cb2e"
name = "BrandMe Community Access"
application_url = "https://app.quixote.university"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,read_customers"

[webhooks]
api_version = "2025-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

  # Handled by: /app/routes/webhooks.orders.paid.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = ["orders/paid"]

  # Handled by: /app/routes/webhooks.refunds.create.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = ["refunds/create"]

  # Handled by: /app/routes/webhooks.collections.update.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/collections/update"
  topics = ["collections/update"]

  # Handled by: /app/routes/webhooks.products.update.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = ["products/update"]

  # Handled by: /app/routes/webhooks.customers.data_request.tsx
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  # Handled by: /app/routes/webhooks.customers.redact.tsx
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  # Handled by: /app/routes/webhooks.shop.redact.tsx
  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[auth]
redirect_urls = ["https://app.quixote.university/api/auth"]

[build]
automatically_update_urls_on_dev = true
